#include "eth_lookup.hpp"

struct eth_proto_name {
    uint16_t proto;
    const char *name;
};

static const struct eth_proto_name eth_proto_names[] = {
    { ETH_P_LOOP,      "Ethernet Loopback packet" },
    { ETH_P_PUP,       "Xerox PUP packet" },
    { ETH_P_PUPAT,     "Xerox PUP Addr Trans packet" },
    { ETH_P_TSN,       "TSN (IEEE 1722) packet" },
    { ETH_P_ERSPAN2,   "ERSPAN version 2" },
    { ETH_P_IP,        "Internet Protocol packet" },
    { ETH_P_X25,       "CCITT X.25" },
    { ETH_P_ARP,       "Address Resolution packet" },
    { ETH_P_BPQ,       "G8BPQ AX.25 Ethernet Packet" },
    { ETH_P_IEEEPUP,   "Xerox IEEE802.3 PUP packet" },
    { ETH_P_IEEEPUPAT, "Xerox IEEE802.3 PUP Addr Trans packet" },
    { ETH_P_BATMAN,    "B.A.T.M.A.N.-Advanced packet" },
    { ETH_P_DEC,       "DEC Assigned protocol" },
    { ETH_P_DNA_DL,    "DEC DNA Dump/Load" },
    { ETH_P_DNA_RC,    "DEC DNA Remote Console" },
    { ETH_P_DNA_RT,    "DEC DNA Routing" },
    { ETH_P_LAT,       "DEC LAT" },
    { ETH_P_DIAG,      "DEC Diagnostics" },
    { ETH_P_CUST,      "DEC Customer use" },
    { ETH_P_SCA,       "DEC Systems Comms Arch" },
    { ETH_P_TEB,       "Trans Ether Bridging" },
    { ETH_P_RARP,      "Reverse Address Resolution" },
    { ETH_P_ATALK,     "AppleTalk DDP" },
    { ETH_P_AARP,      "AppleTalk AARP" },
    { ETH_P_8021Q,     "802.1Q VLAN" },
    { ETH_P_ERSPAN,    "ERSPAN" },
    { ETH_P_IPX,       "IPX over DIX" },
    { ETH_P_IPV6,      "IPv6" },
    { ETH_P_PAUSE,     "IEEE Pause frames" },
    { ETH_P_SLOW,      "Slow Protocol" },
    { ETH_P_WCCP,      "Web Cache Coordination Protocol" },
    { ETH_P_MPLS_UC,   "MPLS Unicast" },
    { ETH_P_MPLS_MC,   "MPLS Multicast" },
    { ETH_P_ATMMPOA,   "MultiProtocol over ATM" },
    { ETH_P_PPP_DISC,  "PPPoE Discovery" },
    { ETH_P_PPP_SES,   "PPPoE Session" },
    { ETH_P_LINK_CTL,  "HPNA / Link Control" },
    { ETH_P_ATMFATE,   "ATM over Ethernet" },
    { ETH_P_PAE,       "802.1X Port Access Entity" },
    { ETH_P_PROFINET,  "PROFINET" },
    { ETH_P_REALTEK,   "Realtek" },
    { ETH_P_AOE,       "ATA over Ethernet" },
    { ETH_P_ETHERCAT,  "EtherCAT" },
    { ETH_P_8021AD,    "802.1ad Service VLAN" },
    { ETH_P_8021AH,    "802.1ah Backbone Service" },
    { ETH_P_1588,      "IEEE 1588" },
    { ETH_P_NCSI,      "NCSI" },
    { ETH_P_PRP,       "PRP" },
    { ETH_P_CFM,       "Connectivity Fault Management" },
    { ETH_P_FCOE,      "Fibre Channel over Ethernet" },
    { ETH_P_TDLS,      "TDLS" },
    { ETH_P_FIP,       "FCoE Initialization Protocol" },
    { ETH_P_80221,     "IEEE 802.21" },
    { ETH_P_HSR,       "High-availability Seamless Redundancy" },
    { ETH_P_NSH,       "Network Service Header" },
    { ETH_P_LOOPBACK,  "Ethernet Loopback" },
    { ETH_P_QINQ1,     "QinQ VLAN" },
    { ETH_P_QINQ2,     "QinQ VLAN" },
    { ETH_P_QINQ3,     "QinQ VLAN" },
    { ETH_P_EDSA,      "Ethernet DSA" },
    { ETH_P_DSA_8021Q, "DSA 802.1Q" },
    { ETH_P_DSA_A5PSW, "A5PSW Tag" },
    { ETH_P_IFE,       "Inter-FE" },
    { ETH_P_AF_IUCV,   "AF_IUCV" },
    { ETH_P_802_3,     "IEEE 802.3" },
    { ETH_P_AX25,      "AX.25" },
    { ETH_P_ALL,       "All protocols" },
    { ETH_P_802_2,     "IEEE 802.2" },
    { ETH_P_SNAP,      "SNAP" },
    { ETH_P_DDCMP,     "DEC DDCMP" },
    { ETH_P_WAN_PPP,   "WAN PPP" },
    { ETH_P_PPP_MP,    "PPP Multilink" },
    { ETH_P_LOCALTALK, "LocalTalk" },
    { ETH_P_CAN,       "CAN" },
    { ETH_P_CANFD,     "CAN FD" },
    { ETH_P_CANXL,     "CAN XL" },
    { ETH_P_PPPTALK,   "PPP Talk" },
    { ETH_P_TR_802_2,  "802.2" },
    { ETH_P_MOBITEX,   "Mobitex" },
    { ETH_P_CONTROL,   "Control" },
    { ETH_P_IRDA,      "IrDA" },
    { ETH_P_ECONET,    "Econet" },
    { ETH_P_HDLC,      "HDLC" },
    { ETH_P_ARCNET,    "ARCnet" },
    { ETH_P_DSA,       "Distributed Switch Architecture" },
    { ETH_P_TRAILER,   "Trailer" },
    { ETH_P_PHONET,    "Phonet" },
    { ETH_P_IEEE802154,"IEEE 802.15.4" },
    { ETH_P_CAIF,      "CAIF" },
    { ETH_P_XDSA,      "Multiplexed DSA" },
    { ETH_P_MAP,       "Multiplexed Aggregation" },
    { ETH_P_MCTP,      "Management Component Transport" },
};

const char *eth_p_human(uint16_t proto)
{
    unsigned long i;
    for (i = 0; i < sizeof(eth_proto_names) / sizeof(eth_proto_names[0]); ++i) {
        if (eth_proto_names[i].proto == proto)
            return eth_proto_names[i].name;
    }
    return "Unknown";
}

